config/routes.rb
Rails.application.routes.draw do
  devise_for :autors
  resources :articulos do
    resources :comentarios
  end
  get 'estaticas/contacto'
  get 'estaticas/nosotros'
  get 'home/index'
  root 'articulos#index'

  get '*path' => redirect('/')
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/articulo.rb
class Articulo < ApplicationRecord
  belongs_to :autor
  has_many :comentarios, dependent: :destroy
  validates :titulo, presence: { message: "no puede estar vacío"}
  validates :contenido, presence: { message: "no puede estar vacío" }, length: {minimum: 3, message: "es demasiado corto"}
end

app/models/autor.rb
class Autor < ApplicationRecord
  has_many :articulos
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/comentario.rb
class Comentario < ApplicationRecord
  belongs_to :articulo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articulos_controller.rb
class ArticulosController < ApplicationController

  before_action :authenticate_autor!, except: [:index, :show]
  before_action :correct_autor, only: [:edit, :update, :destroy]

  def index
    @articulos=Articulo.all.order("created_at DESC").paginate(page: params[:page], per_page: 2)
  end

  def new
    @boton="Crear"
    @articulo = current_autor.articulos.build
  end

  def create
    @articulo = current_autor.articulos.build(articulo_params)
    if @articulo.save 
      redirect_to @articulo 
    else 
      render 'new'
    end
  end

  def edit
    @boton="Editar"
    @articulo=Articulo.find(params[:id])
  end

  def update
    @articulo=Articulo.find(params[:id])
    if @articulo.update(articulo_params)
      flash[:notice] = "Artículo modificado correctamente"
      redirect_to @articulo
    else
      render 'edit'
    end
  end

  def destroy
    @articulo=Articulo.find(params[:id])
    @articulo.destroy
    redirect_to articulos_path, notice: "Artículo eliminado correctamente"
  end

  def show
    @articulo=Articulo.find(params[:id])
  end

  private
    def articulo_params
      params.require(:articulo).permit(:titulo, :contenido)
    end

    def correct_autor
      @articulo = current_autor.articulos.find_by(id: params[:id])
      redirect_to articulos_path, notice: "No estás autorizado a editar este artículo" if @articulo.nil?
    end
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  before_action :set_articulo, only: [:create, :destroy]

  # POST /comentarios or /comentarios.json
  def create
    @comentario = @articulo.comentarios.create(comentario_params)

    redirect_to @articulo
  end

  # DELETE /comentarios/1 or /comentarios/1.json
  def destroy
    @comentario = @articulo.comentarios.find(params[:id])
    @comentario.destroy
    
    redirect_to @articulo
  end

  private
    def comentario_params
      params.require(:comentario).permit(:nombre, :texto, :articulo_id)
    end

    def set_articulo
      @articulo = Articulo.find(params[:articulo_id])
    end
end

app/controllers/estaticas_controller.rb
class EstaticasController < ApplicationController
  def contacto
    @id=params[:id].to_i
    @pagina=params[:pagina]
  end

  def nosotros
    @mensaje = "Hola desde el controller"
    @usuarios = ['Miguel', 'Luis', 'Josué', 'Noé']
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articulos_helper.rb
module ArticulosHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/estaticas_helper.rb
module EstaticasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articulos/_form.html.erb
<div class="row">
    <div class="col-md-6">
        <%= form_for @articulo do |f| %>

            <% if @articulo.errors.any? %>
                <div id="errors">
                    <h2>Se han producido los siguientes errores:</h2>
                    <ul>
                        <% @articulo.errors.full_messages.each do |msg| %>
                            <li><%= msg  %></li>
                        <% end %>
                    </ul>
                </div>
            <% end %>

            <div class="form-group">
                <%= f.label :titulo %>
                <%= f.text_field :titulo, class: "form-control" %>
            </div>

            <div class="form-group">
                <%= f.label :contenido %>
                <%= f.text_area :contenido, class: "form-control" %>
            </div>

            <%= f.submit "#{@boton} Artículo", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/articulos/edit.html.erb
<h1>Editar Articulo</h1>

<%= render 'form'  %>

app/views/articulos/index.html.erb
<h1>Articulos</h1>

<%= link_to "Crear", new_articulo_path %>

<% @articulos.each do |art| %>
    <h2><%= link_to art.titulo, art %></h2>
    <p><small><%= art.created_at.strftime("%d-%m-%Y") %></small></p>
    <p><%= art.contenido.truncate_words(30) %></p>
<% end %>

<%= will_paginate @articulos, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer %>

app/views/articulos/new.html.erb
<h1>Nuevo Articulo</h1>

<%= render 'form'  %>

app/views/articulos/show.html.erb
<h1><%= @articulo.titulo %></h1>

<p><small>Creado el <%= @articulo.created_at.strftime("%d-%m-%Y") %></small></p>
<p><%= @articulo.contenido %></p>

<% if autor_signed_in? %>
    <%= link_to 'Editar', edit_articulo_path(@articulo) %>
    <%= link_to 'Eliminar', @articulo, method: :delete, data: {confirm: "¿Seguro que quieres eliminar el artículo?"} %>
<% end %>

<p><%= @articulo.comentarios.count %> Comentarios</p>
<%= render @articulo.comentarios %>

<p>Deja tu comentario</p>
<%= render 'comentarios/form' %>

app/views/comentarios/_comentario.html.erb
<div>
    <p><%= comentario.nombre %></p>
    <p><%= comentario.texto %></p>
    <p>Creado el <%= comentario.created_at.strftime("%d-%m-%Y") %></p>

    <%= link_to "Eliminar", [comentario.articulo, comentario], method: :delete, data: {confirm: "¿Seguro que quieres eliminar el comentario?"} %>
    <hr>
</div>

    

app/views/comentarios/_form.html.erb
<div class="row">
  <div class="col-md-6">
    <%= form_for([@articulo, @articulo.comentarios.build]) do |form| %>

      <div class="form-group">
        <%= form.label :nombre %>
        <%= form.text_field :nombre, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :texto %>
        <%= form.text_area :texto, class: "form-control" %>
      </div>

      <div class="actions">
        <%= form.submit "Comentar", class: "btn btn-primary" %>
      </div>
    <% end %>

  </div>
</div>

app/views/estaticas/contacto.html.erb
<%= provide(:titulo, 'Contacto') %>

<h1>Contacto</h1>

app/views/estaticas/nosotros.html.erb
<%= provide(:titulo, 'Nosotros') %>

<h1>Nosotros</h1>

app/views/home/index.html.erb
<%= provide(:titulo, 'Home') %>

<h1>Hola</h1>
<div>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Tempora, dolore asperiores veniam consequuntur magnam quos praesentium nam nihil nostrum laudantium quis ipsam non, aspernatur sint voluptate quia illo temporibus ipsa.</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :titulo %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'shared/header' %>
    
    <div class="container">
      <% if !flash.empty? %>
        <div class="alert alert-info">
          <ul>
            <% flash.each do |k, value| %>
              <li><%= value %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container">

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to 'Home', root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Contacto', estaticas_contacto_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Nosotros', estaticas_nosotros_path, class: "nav-link" %>
        </li>
      </ul>

      <div>
        <ul class="navbar-nav navbar-right mr-auto">
          <% if !autor_signed_in? %>
            <li class="nav-item">
              <%= link_to 'Iniciar sesión', new_autor_session_path, class: "nav-link" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Nuevo Artículo', new_articulo_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Cerrar sesión', destroy_autor_session_path, class: "nav-link", method: :delete %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>